const mongoose = require("mongoose");
const productSchema = mongoose.Schema({
    id:{
        type: String
    },
    title:{
        type: String
    },
    description:{
        type: String
    },
    category:{
        type:String
    },
    price:{
        type:String
    },
    discountPercentage:{
        type:String
    },
    rating:{
        type:String
    },
    stock:{
        type:String
    },
    
    brand:{
        type:String
    },
    sku:{
        type:String
    },
    weight:{
        type:String
    },
    dimensions:{
        width:{
            type:String
        },
        height:{
            type:String
        },
        depth:{
            type:String
        }
    },
    warrantyInformation:{
        type:String
    },
    shippingInformation:{
        type:String
    },
    availabilityStatus:{
        type:String
    },
    reviews:[
        {
            rating:{
                type:String
            },
            Comment:{
                type:String
            },
            date:{
                type:String
            },
            reviewerName:{
                type:String
            },
            reviewerEmail:{
                type:String
            }
        }
    ],
    returnPolicy:{
        type:String
    },
    minimumOrderQuantity:{
        type:String
    },
    meta:{
        createAt:{
            type:String
        },
        updatedAt:{
            type:String
        },
        barcode:{
            type:String
        },
        qrCode:{
            type:String
        }
    },
    images:[
        type=String
    ],
    thumbnail:{
        type:String
    }
})

module.exports = mongoose.model("products" , productSchema);